import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white text-[#013667]">
        <nav className="sticky top-0 z-50 border-b border-gray-200 bg-white">
          <div className="mx-auto flex h-20 w-full max-w-7xl items-center justify-between px-6 sm:px-10 lg:px-16">
            <Link href="/" className="text-lg font-extrabold tracking-tight text-[#013667]">
              LOGO
            </Link>
            <div className="flex items-center gap-6 text-sm font-medium text-[#013667]">
              <Link href="/vehicles" className="transition hover:opacity-80">
                Vehicles
              </Link>
              <Link href="/calculator" className="transition hover:opacity-80">
                Calculator
              </Link>
              <Link href="/process" className="transition hover:opacity-80">
                Process
              </Link>
              <Link href="/about" className="transition hover:opacity-80">
                About
              </Link>
            </div>
          </div>
        </nav>

        <main className="flex-1">{children}</main>

        <footer className="border-t border-gray-200 bg-white text-[#013667]">
          <div className="mx-auto flex w-full max-w-7xl flex-col gap-6 px-6 py-10 sm:px-10 lg:px-16">
            <div className="flex flex-wrap items-center gap-5 text-sm">
              <Link href="/vehicles" className="transition hover:opacity-80">
                Vehicles
              </Link>
              <Link href="/calculator" className="transition hover:opacity-80">
                Calculator
              </Link>
              <Link href="/process" className="transition hover:opacity-80">
                Process
              </Link>
              <Link href="/about" className="transition hover:opacity-80">
                About
              </Link>
            </div>
            <p className="text-xs text-gray-500">
              Copyright {new Date().getFullYear()} NextGen Traders. All rights reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
